export default function Tentang(){
    return(
      <main id="tentang">
        <h1>Tentang</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In laoreet eu tortor ut lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed accumsan mi vitae libero tristique sagittis vitae ac dui. Vestibulum sit amet posuere diam, sit amet blandit mi. Aliquam vitae turpis blandit, bibendum neque ac, luctus risus. Fusce dictum tortor at magna ultrices, pulvinar rhoncus leo varius. Cras tincidunt elementum libero malesuada vulputate. Phasellus dapibus mi enim, nec eleifend est egestas vitae. Praesent at tellus turpis. Nunc gravida dapibus urna id pretium. Quisque quis mauris molestie, finibus ante in, dignissim velit. Aenean at lacinia lacus, at mattis arcu.

Fusce eget urna venenatis, venenatis purus sit amet, mollis felis. Aenean vehicula risus ut diam laoreet vulputate. In scelerisque sapien suscipit dui tempor tempus. Aenean consectetur rhoncus quam sed accumsan. Nulla lectus quam, gravida at semper ac, vulputate a neque. Suspendisse posuere arcu feugiat ipsum vestibulum, at luctus ligula pharetra. Donec fringilla feugiat dui eu accumsan. Nunc at libero eu purus ornare rhoncus. Cras condimentum lacus nisl, sit amet varius erat molestie nec. Morbi suscipit lacus nisl, sit amet pharetra nulla condimentum nec. Morbi ornare, felis nec consequat congue, erat odio commodo velit, id porttitor ligula eros eu erat. Proin aliquam tincidunt diam non lobortis. Morbi vitae fringilla tortor. Integer at luctus velit. Fusce efficitur gravida urna, sit amet placerat urna suscipit at. Nullam rhoncus vulputate sapien, et convallis libero venenatis eget.

Nam ipsum sem, commodo non maximus id, dignissim sit amet massa. Nullam auctor tincidunt condimentum. Sed tincidunt hendrerit lacus id porta. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris faucibus lectus in velit pharetra scelerisque. Sed maximus, elit finibus varius scelerisque, risus tellus semper velit, sed sodales dui magna eget nunc. Fusce tincidunt enim tortor, quis maximus lectus tincidunt sed. Maecenas ut lobortis ligula. Aenean auctor a lorem sit amet auctor. Praesent laoreet sem hendrerit mollis mattis. In hac habitasse platea dictumst. Nam nec nunc eu justo congue pellentesque. Integer convallis dignissim urna sed lobortis. Aliquam vitae sodales lorem. Curabitur fringilla tellus nec lectus mattis consectetur. Proin a ligula enim.

Praesent rhoncus consectetur dui, sed tincidunt tortor convallis ac. Praesent a lorem nec mauris iaculis scelerisque. Quisque fermentum elit non orci varius imperdiet. Aenean posuere tortor turpis, nec feugiat lectus hendrerit eu. Donec semper ex sit amet dignissim viverra. Ut pharetra nibh vitae consequat egestas. Donec egestas nibh sed mi euismod, et sodales risus tristique. Donec tempus lorem nec mauris porttitor, quis pretium mauris bibendum. Fusce et velit sed felis accumsan feugiat. Ut scelerisque massa sed consectetur sollicitudin. Morbi venenatis ultricies ante, nec commodo ipsum suscipit quis. Cras vel porttitor ex. Sed efficitur interdum quam, non feugiat urna elementum sit amet.

In laoreet ac dui ut eleifend. Quisque eget erat eget diam convallis faucibus feugiat non purus. In finibus laoreet est, ut venenatis nisi ullamcorper nec. Nam tincidunt enim ante, eu facilisis mi accumsan sit amet. Duis nec vehicula turpis. Fusce ut faucibus urna, non sollicitudin orci. Ut vel ante vitae ante finibus commodo suscipit eget nunc. Nam a libero vitae mi bibendum hendrerit. Quisque mattis sapien ut sapien interdum, id rutrum est vulputate. Aliquam vestibulum eu erat id facilisis. Maecenas nulla nibh, iaculis ut sodales ut, rhoncus a urna.</p>
      </main>
    );
  }